### ISSUE TITLE
To able to modify background padding / margin width.

### ISSUE THREAD

**Issue by sharathGowda12** [pacifio/fancy_drawer#2]
![Untitled](https://user-images.githubusercontent.com/54023637/79565948-502e0400-80cf-11ea-9c2b-7b8818d2e138.png)

Is there any way to modify the width parameters (as marked in image).

**Comment by nizwar** [comment]
Hi, i've done some changes so we able to do exaclty what you need, lets hope the owner accept my pull request and publish it on pub.dev :)

Also you can use this and setup your own drawerPadding
`  fancy_drawer: 
    git: 
      url: 'https://github.com/nizwar/fancy_drawer.git'`

**Comment by pacifio** [comment]
There is a new option called `drawerPadding` which might help this
